server.port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine_hibernate?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 458345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate.ddl-auto: none
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
referrer: http://www.google.com
testWhileIdle : true

indexing-settings:
  sites :
    playback.ru/: playback
    askerweb.by/: askerweb






